# Generated by Django 5.0.6 on 2024-08-09 23:18

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresaprimaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('razao_social', models.CharField(max_length=120)),
                ('CNPJ', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, max_length=1000, upload_to='media/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('setor', models.CharField(choices=[('Jardinagem', 'Jardinagem'), ('Limpeza predial', 'Limpeza predial'), ('Controle de pragas', 'Controle de pragas'), ('Controle de instalações elétricas', 'Controle de instalações elétricas')], max_length=40)),
                ('EmpresaPrimaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaPrimaria', to='empresaprimaria.empresaprimaria')),
            ],
        ),
    ]
