# Generated by Django 5.1 on 2024-10-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresasecundaria',
            name='CNPJ',
        ),
        migrations.RemoveField(
            model_name='empresasecundaria',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='empresasecundaria',
            name='razao_social',
        ),
    ]
