# Generated by Django 5.1 on 2024-09-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresasecundaria',
            old_name='EmpresaPrimaria',
            new_name='empresaprimaria',
        ),
    ]
