# Generated by Django 5.1 on 2024-09-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasecundario', '0002_rename_empresaprimaria_empresasecundaria_empresaprimaria'),
        ('zeladorx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresasecundaria',
            name='setor',
        ),
        migrations.AddField(
            model_name='empresasecundaria',
            name='setor',
            field=models.ManyToManyField(max_length=40, to='zeladorx.typezeladoria'),
        ),
    ]
