# Generated by Django 5.1 on 2024-09-19 22:38

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoDisponiveisJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('Nome', models.CharField(max_length=60)),
                ('DataDeAquisicao', models.DateField()),
                ('DataDeDesmobilizacao', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=12)),
                ('tipoequipamento', models.CharField(choices=[('Proprio', 'Proprio'), ('Terceirizado', 'Terceirizado')], default='Proprio', max_length=60)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaEquipamentosDisponiveisJardinagem', to='empresasecundario.empresasecundaria')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoDisponiveisLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('Nome', models.CharField(max_length=60)),
                ('DataDeAquisicao', models.DateField()),
                ('DataDeDesmobilizacao', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=12)),
                ('tipoequipamento', models.CharField(choices=[('Proprio', 'Proprio'), ('Terceirizado', 'Terceirizado')], default='Proprio', max_length=60)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaEquipamentosDisponiveisLimpezaPredial', to='empresasecundario.empresasecundaria')),
            ],
        ),
    ]
