# Generated by Django 5.1 on 2024-09-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_equipamantos', '0002_alter_catalogodeequipamentos_unique_together_and_more'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentodisponiveis',
            name='Nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RNomeCatalogoEquipamentosJardinagem', to='catalogo_de_equipamantos.catalogodeequipamentosjardinagem'),
        ),
    ]
