# Generated by Django 5.1 on 2024-09-09 16:27

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_equipamantos', '0003_delete_catalogodeequipamentos_and_more'),
        ('empresasecundario', '0001_initial'),
        ('equipamentos', '0002_alter_equipamentodisponiveis_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipamentodisponiveis',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='equipamentodisponiveis',
            name='EmpresaSecundaria',
        ),
        migrations.RemoveField(
            model_name='equipamentodisponiveis',
            name='Nome',
        ),
        migrations.CreateModel(
            name='EquipamentoDisponiveisJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('DataDeAquisicao', models.DateField()),
                ('DataDeDesmobilizacao', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=12)),
                ('tipoequipamento', models.CharField(choices=[('Proprio', 'Proprio'), ('Terceirizado', 'Terceirizado')], default='Proprio', max_length=60)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaEquipamentosDisponiveisJardinagem', to='empresasecundario.empresasecundaria')),
                ('Nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RNomeCatalogoEquipamentosJardinagem', to='catalogo_de_equipamantos.catalogodeequipamentosjardinagem')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoDisponiveisLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('DataDeAquisicao', models.DateField()),
                ('DataDeDesmobilizacao', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=12)),
                ('tipoequipamento', models.CharField(choices=[('Proprio', 'Proprio'), ('Terceirizado', 'Terceirizado')], default='Proprio', max_length=60)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaEquipamentosDisponiveisLimpezaPredial', to='empresasecundario.empresasecundaria')),
                ('Nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RNomeCatalogoEquipamentosLimpezaPredial', to='catalogo_de_equipamantos.catalogodeequipamentoslimpezapredial')),
            ],
        ),
    ]
