# Generated by Django 5.1 on 2024-09-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_equipamentodisponiveis_unique_together_and_more'),
        ('servicos', '0002_alter_fatoservicojardinagem_equipamentousado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipamentoDisponiveis',
        ),
        migrations.AlterUniqueTogether(
            name='equipamentodisponiveisjardinagem',
            unique_together={('Nome', 'EmpresaSecundaria')},
        ),
        migrations.AlterUniqueTogether(
            name='equipamentodisponiveislimpezapredial',
            unique_together={('Nome', 'EmpresaSecundaria')},
        ),
    ]
