# Generated by Django 5.1.4 on 2025-01-02 01:53

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('dimensao', models.FloatField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, max_length=2000, upload_to='areaslimpezapredial/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AreasJardins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('dimensao', models.FloatField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, max_length=2000, upload_to='areasverdes/%Y/%m/%d/')),
                ('periodicidade', models.CharField(choices=[('Mensal', 'Mensal'), ('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensal', max_length=30)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
            ],
        ),
    ]
