# Generated by Django 5.0.6 on 2024-08-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('catalogo_de_servicos', '0001_initial'),
        ('localidade', '0001_initial'),
        ('servicos', '0001_initial'),
        ('terrenos', '0001_initial'),
        ('vegetacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Areas',
            new_name='AreasJardins',
        ),
    ]
