# Generated by Django 5.1.4 on 2025-01-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('catalogo_de_servicos', '0002_initial'),
        ('localidade', '0001_initial'),
        ('terrenos', '0001_initial'),
        ('vegetacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealimpezapredial',
            name='localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidadelimpezapredial', to='localidade.localidadelimpezapredial'),
        ),
        migrations.AddField(
            model_name='arealimpezapredial',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicocatalogoservicolimpezapredial', to='catalogo_de_servicos.catalogodeservicolimpezapredial'),
        ),
        migrations.AddField(
            model_name='areasjardins',
            name='Terreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rTerrenoAreas', to='terrenos.terreno'),
        ),
        migrations.AddField(
            model_name='areasjardins',
            name='localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidadeareas', to='localidade.localidadejardiangem'),
        ),
        migrations.AddField(
            model_name='areasjardins',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicocatalogoservico', to='catalogo_de_servicos.catalogodeservicojardinagem'),
        ),
        migrations.AddField(
            model_name='areasjardins',
            name='vegetacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetacaocatalogovegetacao', to='vegetacao.catalogovegetacao'),
        ),
        migrations.AlterUniqueTogether(
            name='arealimpezapredial',
            unique_together={('nome', 'localidade')},
        ),
        migrations.AlterUniqueTogether(
            name='areasjardins',
            unique_together={('nome', 'vegetacao', 'Terreno')},
        ),
    ]
