# Generated by Django 5.0.6 on 2024-08-12 01:38

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_rename_areas_areasjardins'),
        ('localidade', '0003_alter_localidadejardiangem_unidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('dimensao', models.FloatField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidadelimpezapredial', to='localidade.localidadelimpezapredial')),
            ],
        ),
    ]
