# Generated by Django 5.0.6 on 2024-08-12 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_arealimpezapredial'),
        ('catalogo_de_servicos', '0003_alter_catalogodeservicojardinagem_empresasecundaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealimpezapredial',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicocatalogoservicolimpezapredial', to='catalogo_de_servicos.catalogodeservicolimpezapredial'),
        ),
        migrations.AlterUniqueTogether(
            name='arealimpezapredial',
            unique_together={('nome', 'localidade')},
        ),
    ]
