# Generated by Django 5.1.4 on 2025-08-22 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0002_alter_arealimpezapredial_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeAreaJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('imagem_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/jardinagem')),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.areasjardins')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacoesJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.areasjardins')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rUSERAprovals', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rUSERCreator', to=settings.AUTH_USER_MODEL)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.qrcodeareajardinagem')),
            ],
        ),
    ]
