# Generated by Django 5.1.4 on 2025-08-22 15:06

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeareajardinagem',
            name='id_random',
            field=models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='solicitacoesjardinagem',
            name='id_random',
            field=models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True),
        ),
    ]
