# Generated by Django 5.1.4 on 2025-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_qrcodeareajardinagem_id_random_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoesjardinagem',
            name='descricao',
            field=models.TextField(blank=False, max_length=2000, null=False),
        ),
    ]
