# Generated by Django 5.1.4 on 2025-08-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_alter_solicitacoesjardinagem_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoesjardinagem',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
    ]
