# Generated by Django 5.1.4 on 2025-08-25 21:29

import django.db.models.deletion
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_arealimpezapredial_unique_together_and_more'),
        ('solicitacoes', '0004_alter_solicitacoesjardinagem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeAreaLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('imagem_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/limpeza_predial')),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.arealimpezapredial')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacoesLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('descricao', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.arealimpezapredial')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rUSERAprovalslp', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rUSERCreatorlo', to=settings.AUTH_USER_MODEL)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.qrcodearealimpezapredial')),
            ],
        ),
    ]
