# Generated by Django 5.1.4 on 2025-08-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_qrcodearealimpezapredial_solicitacoeslimpezapredial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoesjardinagem',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacoeslimpezapredial',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20),
        ),
    ]
