# Generated by Django 5.1.4 on 2025-08-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_alter_solicitacoesjardinagem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoesjardinagem',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitacoes.qrcodeareajardinagem'),
        ),
        migrations.AlterField(
            model_name='solicitacoeslimpezapredial',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitacoes.qrcodearealimpezapredial'),
        ),
    ]
