# Generated by Django 5.1.4 on 2025-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_alter_solicitacoesjardinagem_qrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeareajardinagem',
            name='status',
            field=models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60),
        ),
        migrations.AddField(
            model_name='qrcodearealimpezapredial',
            name='status',
            field=models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60),
        ),
    ]
