# Generated by Django 5.1 on 2024-09-09 15:59

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_equipamantos', '0001_initial'),
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogodeequipamentos',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='catalogodeequipamentos',
            name='EmpresaSecundaria',
        ),
        migrations.CreateModel(
            name='CatalogoDeEquipamentosJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoEquipamentosJardinagem', to='empresasecundario.empresasecundaria')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDeEquipamentosLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoEquipamentosLimpezaPredial', to='empresasecundario.empresasecundaria')),
            ],
        ),
    ]
