# Generated by Django 5.1 on 2024-09-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_equipamantos', '0002_alter_catalogodeequipamentos_unique_together_and_more'),
        ('equipamentos', '0002_alter_equipamentodisponiveis_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoDeEquipamentos',
        ),
        migrations.AlterUniqueTogether(
            name='catalogodeequipamentosjardinagem',
            unique_together={('nome', 'EmpresaSecundaria')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogodeequipamentoslimpezapredial',
            unique_together={('nome', 'EmpresaSecundaria')},
        ),
    ]
