# Generated by Django 5.0.6 on 2024-08-09 23:18

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('funcao', models.CharField(max_length=100)),
                ('atividades', models.TextField(max_length=150)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizacao Permanente', 'Desmobilizacao Permanente')], default='Mobilizado', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
