# Generated by Django 5.0.6 on 2024-08-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colaborador', '0001_initial'),
        ('gerente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='gerente',
            field=models.ManyToManyField(related_name='Rgerentegerenteorigem', to='gerente.gerente'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='colaborador_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='colaborador_permissions_set', to='auth.permission'),
        ),
    ]
