# Generated by Django 5.0.6 on 2024-08-09 23:18

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0002_initial'),
        ('gerente', '0001_initial'),
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingServicosColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('AceitarTodosOsServicos', models.BooleanField(blank=True, default=True, null=True)),
                ('RejeitarServicosPartirDe', models.DateTimeField(blank=True, null=True)),
                ('RejeitarServicosAte', models.DateTimeField(blank=True, null=True)),
                ('NotificationsNewService', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServiceCanceled', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsAlterService', models.BooleanField(blank=True, default=False, null=True)),
                ('Colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RColaboradorSettingServicosColaborador', to='colaborador.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='SettingServicosGerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('ServicoCompunsivo', models.BooleanField(blank=True, default=False, null=True)),
                ('TempoPadraoServico', models.DurationField(blank=True, null=True)),
                ('NotificationToColaboborador', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationAceptReject', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationEndService', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationCancelService', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationNewService', models.BooleanField(blank=True, default=False, null=True)),
                ('Gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RGerenteSettingServicosGerente', to='gerente.gerente')),
            ],
        ),
        migrations.CreateModel(
            name='SettingServicosGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('ServicoCompunsivo', models.BooleanField(blank=True, default=False, null=True)),
                ('TempoPadraoServico', models.DurationField(blank=True, null=True)),
                ('NotificationToColaboborador', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationAceptReject', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationEndService', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationCancelService', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationNewService', models.BooleanField(blank=True, default=False, null=True)),
                ('Gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RGestorSettingServicosGestor', to='gestor.gestor')),
            ],
        ),
    ]
