# Generated by Django 5.1 on 2024-09-27 02:14

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingServicosGerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('ServicoCompunsivo', models.BooleanField(blank=True, default=False, null=True)),
                ('TempoPadraoServico', models.DurationField(blank=True, null=True)),
                ('NotificationToColaboborador', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationAceptReject', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationEndService', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationCancelService', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationNewService', models.BooleanField(blank=True, default=False, null=True)),
                ('Gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RGerenteSettingServicosGerente', to='gerente.gerente')),
            ],
        ),
    ]
