# Generated by Django 5.1.4 on 2025-03-25 12:41

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0001_initial'),
        ('settings', '0002_settingservicosgerentejardinagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingservicosgerentejardinagem',
            name='Gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RGerenteSettingServicosJardinagemGerente', to='gerente.gerente'),
        ),
        migrations.CreateModel(
            name='SettingServicosGerenteLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('NotificationsServicosAtrasados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosProximos', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosEmAndamento', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosCancelados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationsServicosAgendados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportProductivity', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosAtrasados', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosProximos', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosEmAndamento', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationReportServicosCancelados', models.BooleanField(blank=True, default=False, null=True)),
                ('Gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RGerenteSettingServicosLimpezaPredialGerente', to='gerente.gerente')),
            ],
        ),
    ]
