# Generated by Django 5.1 on 2024-09-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissionscontrol', '0004_permissionslimpezapredial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsaccesslimpezapredial',
            name='Permissions',
            field=models.ManyToManyField(related_name='RPermissionsAccessLimpezaPredial', to='permissionscontrol.permissionslimpezapredial'),
        ),
    ]
