# Generated by Django 5.1 on 2024-09-13 18:43

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0003_remove_gerente_empresasecundaria_and_more'),
        ('permissionscontrol', '0008_alter_permissionsjardinagem_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsEspecials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('Permissions', models.CharField(choices=[('340: Pode criar novas unidades', '340: Pode criar novas unidades'), ('341: Pode editar unidades', '341: Pode editar unidades'), ('342: Pode visualizar unidades', '342: Pode visualizar unidades'), ('343: Pode excluir unidades', '343: Pode excluir unidades'), ('344: Pode desmobilizar unidades', '344: Pode desmobilizar unidades'), ('345: Pode reabilitar unidades', '345: Pode reabilitar unidades')], max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsAccessEspecials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('Gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerente.gerente')),
                ('Permissions', models.ManyToManyField(related_name='RPermissionsAccessEspecials', to='permissionscontrol.permissionsespecials')),
            ],
        ),
    ]
