# Generated by Django 5.1 on 2024-09-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissionscontrol', '0009_permissionsespecials_permissionsaccessespecials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsespecials',
            name='Permissions',
            field=models.CharField(choices=[('300: Pode editar permissões especiais', '300: Pode editar permissões especiais'), ('301: Pode visualizar permissões especiais', '301: Pode visualizar permissões especiais'), ('340: Pode criar novas unidades', '340: Pode criar novas unidades'), ('341: Pode editar unidades', '341: Pode editar unidades'), ('342: Pode visualizar unidades', '342: Pode visualizar unidades'), ('343: Pode excluir unidades', '343: Pode excluir unidades'), ('344: Pode desmobilizar unidades', '344: Pode desmobilizar unidades'), ('345: Pode reabilitar unidades', '345: Pode reabilitar unidades')], max_length=75, unique=True),
        ),
    ]
