# Generated by Django 5.1 on 2024-09-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
