# Generated by Django 5.1 on 2024-09-06 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasecundario', '0001_initial'),
        ('gerente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='EmpresaSecundaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariagestor', to='empresasecundario.empresasecundaria'),
            preserve_default=False,
        ),
    ]
