# Generated by Django 5.0.6 on 2024-08-09 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gerente', '0001_initial'),
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestororigem', to='gestor.gestor'),
        ),
        migrations.AddField(
            model_name='gerente',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='gerente_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='gerente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='gerente_permissions_set', to='auth.permission'),
        ),
    ]
