# Generated by Django 5.1.4 on 2025-06-27 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasecundario', '0001_initial'),
        ('gerente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gerente',
            old_name='superuser',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='gerente',
            name='empresasecundaria',
            field=models.ManyToManyField(related_name='gerentes', to='empresasecundario.empresasecundaria'),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerente',
            name='status',
            field=models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=20),
        ),
    ]
