# Generated by Django 5.1 on 2024-09-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0002_remove_gerente_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
