# Generated by Django 5.1 on 2024-09-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0002_gerente_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerente',
            name='foto',
        ),
    ]
