# Generated by Django 5.1 on 2024-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasecundario', '0001_initial'),
        ('gerente', '0002_gerente_empresasecundaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerente',
            name='EmpresaSecundaria',
        ),
        migrations.AddField(
            model_name='gerente',
            name='EmpresaSecundaria',
            field=models.ManyToManyField(related_name='REmpresaSecundariagerente', to='empresasecundario.empresasecundaria'),
        ),
    ]
