headers_report_services = [
    'Tipo de empresa',
    'Empresa',
    'ID Agendamento',
    'Tipo de agendamento',
    'Descrição do Serviço',
    'Serviços Solicitados',
    'Data de Início',
    'Data de conclusao',
    'Status do Serviço',
    'Área atendida',
    'Área total',
    'Localidade',
    'Unidade',
    'ID de serviço',
    'Tempo na área',
    'Colaborador envolvido',
    'Id random colaborador',
    'Depois',
    'Data e hora de chagada',
    'Data e hora de retorno',
    'Id random área',
]

headers_report_services_schedules = [
    'Tipo de empresa',
    'Empresa',
    'ID Agendamento',
    'Tipo de agendamento',
    'Descrição do Serviço',
    'Serviços Solicitados',
    'Data de Início',
    'Data de conclusao',
    'Status do Serviço',
    'Área atendida',
    'Área total',
    'Localidade',
    'Unidade',
    'Id random área',
]