headers_report_services = [
    'Tipo de empresa',
    'Empresa',
    'ID Agendamento',
    'Tipo de agendamento',
    'Descrição do Serviço',
    'Colaboradores Chamados',
    'Serviços Solicitados',
    'Data de Início',
    'Data de conclusao',
    'Antes',
    'Depois',
    'Status do Serviço',
    'Área atendida',
    'Id random área',
    'Periodicidade',
    'Área total',
    'Tipo vegetação',
    'Tipo Terreno',
    'Localidade',
    'Unidade',
    'ID de serviço',
    'Tempo na área',
    'Colaborador envolvido',
    'Id random',
    'Data e hora de chagada',
    'Data e hora de retorno'
]

headers_report_schedules = [
    'Tipo de empresa',
    'Empresa',
    'ID Agendamento',
    'Tipo de agendamento',
    'Descrição do Serviço',
    'Colaboradores Chamados',
    'Serviços Solicitados',
    'Data de Início',
    'Data de conclusao',
    'Antes',
    'Depois',
    'Status do Serviço',
    'Área atendida',
    'Periodicidade',
    'Área total',
    'Tipo vegetação',
    'Tipo Terreno',
    'Localidade',
    'Unidade',
    'Id random área',
]
