# Generated by Django 5.0.6 on 2024-08-09 23:18

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('catalogo_de_servicos', '0001_initial'),
        ('colaborador', '0001_initial'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('DataDeInicio', models.DateTimeField()),
                ('DescricaoDoServico', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Agendado', max_length=60)),
                ('foto_solicitacao', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('foto_entrega', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('DataDeConclusao', models.DateTimeField(blank=True, null=True)),
                ('TipoServico', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Extra', 'Extra')], default='Regular', max_length=30, null=True)),
                ('ServicoCompunsivo', models.BooleanField(blank=True, default=False, null=True)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RAreasServicoAgendado', to='areas.areas')),
                ('ColaboradoresConfirmados', models.ManyToManyField(blank=True, null=True, related_name='RColaboradoresConfirmados', to='colaborador.colaborador')),
                ('ColaboradoresEscalados', models.ManyToManyField(related_name='RColaboradoresEscaladosServicoAgendado', to='colaborador.colaborador')),
                ('ColaboradoresNegados', models.ManyToManyField(blank=True, null=True, related_name='RColaboradoresNegados', to='colaborador.colaborador')),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosServicoAgendado', to='catalogo_de_servicos.catalogodeservico')),
            ],
        ),
        migrations.CreateModel(
            name='FatoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('data_hora_chegada_na_area', models.DateTimeField()),
                ('data_hora_retorno_area', models.DateTimeField()),
                ('Colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RColaboradorFatoServico', to='colaborador.colaborador')),
                ('EquipamentoUsado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REquipamentoUsadoFatoServico', to='equipamentos.equipamentodisponiveis')),
                ('Servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RServicoServicoAgendado', to='servicos.servicoagendado')),
            ],
        ),
    ]
