# Generated by Django 5.1.4 on 2024-12-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicojardinagemagendado',
            name='foto_entrega',
            field=models.ImageField(blank=True, max_length=2000, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='servicojardinagemagendado',
            name='foto_solicitacao',
            field=models.ImageField(blank=True, max_length=2000, upload_to='media/%Y/%m/%d/'),
        ),
    ]
