# Generated by Django 5.1 on 2024-09-19 02:05

import datetime
import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('catalogo_de_servicos', '0001_initial'),
        ('semana', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicojardinagemagendado',
            name='TipoServico',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Extra', 'Extra'), ('Automático', 'Automático')], default='Regular', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='servicolimpezapredialconfigurado',
            name='diasaseremrealizado',
            field=models.ManyToManyField(related_name='Rdiasdasemanaconfiguracoeslimpezapreidal', to='semana.diasdasemana'),
        ),
        migrations.CreateModel(
            name='ServicoJardinagemConfigurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('tempomedioplanejado', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('horario_1', models.TimeField()),
                ('horario_2', models.TimeField(blank=True, null=True)),
                ('horario_3', models.TimeField(blank=True, null=True)),
                ('horario_4', models.TimeField(blank=True, null=True)),
                ('horario_5', models.TimeField(blank=True, null=True)),
                ('horario_6', models.TimeField(blank=True, null=True)),
                ('horario_7', models.TimeField(blank=True, null=True)),
                ('horario_8', models.TimeField(blank=True, null=True)),
                ('horario_9', models.TimeField(blank=True, null=True)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RareaJardinagemconfigurado', to='areas.areasjardins')),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosJardinagemServicoConfigurado', to='catalogo_de_servicos.catalogodeservicojardinagem')),
                ('diasaseremrealizado', models.ManyToManyField(related_name='Rdiasdasemanaconfiguracoesjardinagem', to='semana.diasdasemana')),
            ],
        ),
    ]
