# Generated by Django 5.1 on 2024-09-09 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_equipamentodisponiveis_unique_together_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatoservicojardinagem',
            name='EquipamentoUsado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REquipamentoUsadoFatoServico', to='equipamentos.equipamentodisponiveisjardinagem'),
        ),
    ]
