# Generated by Django 5.0.6 on 2024-08-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_arealimpezapredial_servico_and_more'),
        ('catalogo_de_servicos', '0003_alter_catalogodeservicojardinagem_empresasecundaria_and_more'),
        ('colaborador', '0002_initial'),
        ('equipamentos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FatoServico',
            new_name='FatoServicoJardinagem',
        ),
        migrations.RenameModel(
            old_name='ServicoAgendado',
            new_name='ServicoJardinagemAgendado',
        ),
    ]
