# Generated by Django 5.1 on 2024-08-17 23:00

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_arealimpezapredial_servico_and_more'),
        ('catalogo_de_servicos', '0003_alter_catalogodeservicojardinagem_empresasecundaria_and_more'),
        ('colaborador', '0002_initial'),
        ('servicos', '0002_rename_fatoservico_fatoservicojardinagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('horario_1', models.TimeField(blank=True, null=True)),
                ('horario_2', models.TimeField(blank=True, null=True)),
                ('horario_3', models.TimeField(blank=True, null=True)),
                ('horario_4', models.TimeField(blank=True, null=True)),
                ('horario_5', models.TimeField(blank=True, null=True)),
                ('horario_6', models.TimeField(blank=True, null=True)),
                ('horario_7', models.TimeField(blank=True, null=True)),
                ('horario_8', models.TimeField(blank=True, null=True)),
                ('horario_9', models.TimeField(blank=True, null=True)),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosLimpezaPredialServicoAgendado', to='catalogo_de_servicos.catalogodeservicolimpezapredial')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rarealimpezapredial', to='areas.arealimpezapredial')),
            ],
        ),
        migrations.CreateModel(
            name='FatoServicoLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('data_hora_chegada_na_area', models.DateTimeField()),
                ('data_hora_retorno_area', models.DateTimeField()),
                ('Colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RColaboradorFatoServicoLimpezaPredial', to='colaborador.colaborador')),
                ('Servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RServicoServicoLimpezaPredialAgendado', to='servicos.servicolimpezapredial')),
            ],
        ),
    ]
