# Generated by Django 5.1 on 2024-09-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_fatoservicojardinagem_equipamentousado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicolimpezapredialagendado',
            old_name='area',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='servicolimpezapredialconfigurado',
            old_name='area',
            new_name='Area',
        ),
    ]
