# Generated by Django 5.1 on 2024-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servicojardinagemagendado_tiposervico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicojardinagemconfigurado',
            name='status',
            field=models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60),
        ),
        migrations.AddField(
            model_name='servicolimpezapredialconfigurado',
            name='status',
            field=models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60),
        ),
    ]
