# Generated by Django 5.1 on 2024-09-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servicojardinagemconfigurado_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicojardinagemconfigurado',
            name='horario_8',
        ),
        migrations.RemoveField(
            model_name='servicojardinagemconfigurado',
            name='horario_9',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialconfigurado',
            name='horario_8',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialconfigurado',
            name='horario_9',
        ),
    ]
