# Generated by Django 5.0.6 on 2024-08-18 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servicolimpezapredial_fatoservicolimpezapredial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicolimpezapredial',
            name='tempomedioplanejado',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
