# Generated by Django 5.1 on 2024-09-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_rename_area_servicolimpezapredialagendado_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicolimpezapredialagendado',
            old_name='Area',
            new_name='Areas',
        ),
        migrations.RenameField(
            model_name='servicolimpezapredialconfigurado',
            old_name='Area',
            new_name='Areas',
        ),
    ]
