# Generated by Django 5.1 on 2024-09-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_rename_area_servicolimpezapredialagendado_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicolimpezapredialagendado',
            name='TipoServico',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Extra', 'Extra'), ('Automático', 'Automático')], default='Regular', max_length=30, null=True),
        ),
    ]
