# Generated by Django 5.1 on 2024-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_remove_servicojardinagemconfigurado_horario_8_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicojardinagemagendado',
            name='id_configuracao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicolimpezapredialagendado',
            name='id_configuracao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
