# Generated by Django 5.0.6 on 2024-08-20 00:39

import datetime
import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_arealimpezapredial_servico_and_more'),
        ('catalogo_de_servicos', '0003_alter_catalogodeservicojardinagem_empresasecundaria_and_more'),
        ('servicos', '0004_servicolimpezapredial_tempomedioplanejado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoLimpezaPredialAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('tempomedioplanejado', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('horario_1', models.TimeField()),
                ('horario_2', models.TimeField(blank=True, null=True)),
                ('horario_3', models.TimeField(blank=True, null=True)),
                ('horario_4', models.TimeField(blank=True, null=True)),
                ('horario_5', models.TimeField(blank=True, null=True)),
                ('horario_6', models.TimeField(blank=True, null=True)),
                ('horario_7', models.TimeField(blank=True, null=True)),
                ('horario_8', models.TimeField(blank=True, null=True)),
                ('horario_9', models.TimeField(blank=True, null=True)),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosLimpezaPredialServicoAgendado', to='catalogo_de_servicos.catalogodeservicolimpezapredial')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rarealimpezapredialagendado', to='areas.arealimpezapredial')),
            ],
        ),
        migrations.AlterField(
            model_name='fatoservicolimpezapredial',
            name='Servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RServicoServicoLimpezaPredialAgendado', to='servicos.servicolimpezapredialagendado'),
        ),
        migrations.CreateModel(
            name='ServicoLimpezaPredialConfigurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('tempomedioplanejado', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('horario_1', models.TimeField()),
                ('horario_2', models.TimeField(blank=True, null=True)),
                ('horario_3', models.TimeField(blank=True, null=True)),
                ('horario_4', models.TimeField(blank=True, null=True)),
                ('horario_5', models.TimeField(blank=True, null=True)),
                ('horario_6', models.TimeField(blank=True, null=True)),
                ('horario_7', models.TimeField(blank=True, null=True)),
                ('horario_8', models.TimeField(blank=True, null=True)),
                ('horario_9', models.TimeField(blank=True, null=True)),
                ('ServicosEscalados', models.ManyToManyField(related_name='RServicosEscaladosLimpezaPredialServicoConfigurado', to='catalogo_de_servicos.catalogodeservicolimpezapredial')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rarealimpezapredialconfigurado', to='areas.arealimpezapredial')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicoLimpezaPredial',
        ),
    ]
