# Generated by Django 5.0.6 on 2024-08-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servicolimpezapredialagendado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicolimpezapredialagendado',
            name='DataDeInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicolimpezapredialconfigurado',
            name='diasaseremrealizado',
            field=models.CharField(choices=[('Segunda-Feira', 'Segunda-Feira'), ('Terça-Feira', 'Terça-Feira'), ('Quarta-Feira', 'Quarta-Feira'), ('Quinta-Feira', 'Quinta-Feira'), ('Sexta-Feira', 'Sexta-Feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Quarta-Feira', max_length=50),
        ),
    ]
