# Generated by Django 5.1 on 2024-09-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servicolimpezapredialagendado_tiposervico'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatoservicolimpezapredial',
            name='foto_entrega',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
