# Generated by Django 5.0.6 on 2024-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_servicolimpezapredialagendado_datadeinicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_1',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_2',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_3',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_4',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_5',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_6',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_7',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_8',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='horario_9',
        ),
        migrations.RemoveField(
            model_name='servicolimpezapredialagendado',
            name='tempomedioplanejado',
        ),
        migrations.AddField(
            model_name='servicolimpezapredialagendado',
            name='DataDeConclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicolimpezapredialconfigurado',
            name='diasaseremrealizado',
            field=models.CharField(choices=[('Segunda-Feira', 'Segunda-Feira'), ('Terça-Feira', 'Terça-Feira'), ('Quarta-Feira', 'Quarta-Feira'), ('Quinta-Feira', 'Quinta-Feira'), ('Sexta-Feira', 'Sexta-Feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='', max_length=50),
        ),
    ]
