# Generated by Django 5.1 on 2024-09-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_delete_equipamentodisponiveis_and_more'),
        ('servicos', '0006_fatoservicolimpezapredial_foto_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatoservicojardinagem',
            name='EquipamentoUsado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REquipamentoUsadoFatoServico', to='equipamentos.equipamentodisponiveisjardinagem'),
        ),
    ]
