# Generated by Django 5.0.6 on 2024-08-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0001_initial'),
        ('servicos', '0007_remove_servicolimpezapredialagendado_horario_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicolimpezapredialconfigurado',
            name='diasaseremrealizado',
        ),
        migrations.AddField(
            model_name='servicolimpezapredialconfigurado',
            name='diasaseremrealizado',
            field=models.ManyToManyField(related_name='Rsemanadiasdasemana', to='semana.diasdasemana'),
        ),
    ]
