# Generated by Django 5.1 on 2024-09-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_remove_servicolimpezapredialagendado_horario_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicolimpezapredialagendado',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Agendado', max_length=60),
        ),
    ]
