# Generated by Django 5.1 on 2024-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_servicolimpezapredialagendado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicolimpezapredialagendado',
            name='DescricaoDoServico',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
