# Generated by Django 5.0.6 on 2024-08-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_remove_servicolimpezapredialconfigurado_diasaseremrealizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicolimpezapredialagendado',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Agendado', max_length=60),
        ),
    ]
