# Generated by Django 5.1 on 2024-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0001_initial'),
        ('servicos', '0009_servicolimpezapredialagendado_descricaodoservico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicolimpezapredialconfigurado',
            name='diasaseremrealizado',
        ),
        migrations.AddField(
            model_name='servicolimpezapredialconfigurado',
            name='diasaseremrealizado',
            field=models.ManyToManyField(related_name='Rdiasdasemana', to='semana.diasdasemana'),
        ),
    ]
