# Generated by Django 5.0.6 on 2024-08-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_servicolimpezapredialagendado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicolimpezapredialagendado',
            name='DescricaoDoServico',
            field=models.TextField(default='teste', max_length=200),
            preserve_default=False,
        ),
    ]
