# Generated by Django 5.1.4 on 2025-02-10 23:43

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foruns_criados', to='gerente.gerente')),
                ('participantes', models.ManyToManyField(related_name='foruns_participantes', to='gerente.gerente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemJardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('conteudo', models.TextField()),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('arquivo', 'Arquivo')], default='texto', max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='chats/arquivos/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chats.forumjardinagem')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerente.gerente')),
            ],
            options={
                'ordering': ['-enviado_em'],
            },
        ),
    ]
