# Generated by Django 5.0.6 on 2024-08-09 23:18

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('lat_med', models.FloatField()),
                ('long_med', models.FloatField()),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidadelocalidade', to='unidade.unidade')),
            ],
            options={
                'unique_together': {('nome', 'unidade')},
            },
        ),
    ]
