# Generated by Django 5.0.6 on 2024-08-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_rename_areas_areasjardins'),
        ('localidade', '0001_initial'),
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localidade',
            new_name='LocalidadeJardiangem',
        ),
    ]
