# Generated by Django 5.0.6 on 2024-08-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_rename_areas_areasjardins'),
        ('catalogo_de_servicos', '0001_initial'),
        ('empresasecundario', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogodeServico',
            new_name='CatalogodeServicoJardinagem',
        ),
    ]
