# Generated by Django 5.1.4 on 2025-01-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo_de_servicos', '0001_initial'),
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogodeservicojardinagem',
            name='EmpresaSecundaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoServicoJardiangem', to='empresasecundario.empresasecundaria'),
        ),
        migrations.AddField(
            model_name='catalogodeservicolimpezapredial',
            name='EmpresaSecundaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoServicoLimpezaPredial', to='empresasecundario.empresasecundaria'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogodeservicojardinagem',
            unique_together={('nome', 'EmpresaSecundaria')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogodeservicolimpezapredial',
            unique_together={('nome', 'EmpresaSecundaria')},
        ),
    ]
