# Generated by Django 5.1 on 2024-09-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogodeservicojardinagem',
            name='status',
            field=models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60),
        ),
        migrations.AlterField(
            model_name='catalogodeservicolimpezapredial',
            name='status',
            field=models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60),
        ),
    ]
