# Generated by Django 5.0.6 on 2024-08-12 01:38

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_servicos', '0002_rename_catalogodeservico_catalogodeservicojardinagem'),
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogodeservicojardinagem',
            name='EmpresaSecundaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoServicoJardiangem', to='empresasecundario.empresasecundaria'),
        ),
        migrations.CreateModel(
            name='CatalogodeServicoLimpezaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoServicoLimpezaPredial', to='empresasecundario.empresasecundaria')),
            ],
            options={
                'unique_together': {('nome', 'EmpresaSecundaria')},
            },
        ),
    ]
