# Generated by Django 5.1 on 2024-09-27 02:14

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('linkmapajardinagem', models.CharField(blank=True, max_length=300, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('empresasecundaria', models.ManyToManyField(related_name='REmpresaSecundariaUnidade', to='empresasecundario.empresasecundaria')),
            ],
        ),
    ]
