# Generated by Django 5.1 on 2024-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasecundario', '0002_rename_empresaprimaria_empresasecundaria_empresaprimaria'),
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unidade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='EmpresaSecundaria',
        ),
        migrations.AddField(
            model_name='unidade',
            name='empresasecundaria',
            field=models.ManyToManyField(related_name='REmpresaSecundariaUnidade', to='empresasecundario.empresasecundaria'),
        ),
    ]
