# Generated by Django 5.1 on 2024-09-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_alter_unidade_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidade',
            old_name='linkmapa',
            new_name='linkmapajardinagem',
        ),
    ]
