# Generated by Django 5.1 on 2024-09-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_alter_unidade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='linkmapalimnpezapredial',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
