# Generated by Django 5.1.4 on 2025-01-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistjardinagem',
            name='descricao',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistlimpezapredial',
            name='descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
