# Generated by Django 5.1.4 on 2025-01-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklistjardinagem_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistjardinagem',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklistlimpezapredial',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=20),
        ),
    ]
