# Generated by Django 5.1.4 on 2025-01-19 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_checklistjardinagem_status_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistjardinagem',
            name='servico_agendado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rServicoAgendadosToChecklist', to='servicos.servicojardinagemagendado'),
        ),
    ]
