# Generated by Django 5.1 on 2024-09-18 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresasecundario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDeFerramentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaCatalogoFerramentas', to='empresasecundario.empresasecundaria')),
            ],
            options={
                'unique_together': {('nome', 'EmpresaSecundaria')},
            },
        ),
        migrations.CreateModel(
            name='FerramentasDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataDeAquisicao', models.DateField()),
                ('DataDeDesmobilizacao', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaFerramentasDisponiveis', to='empresasecundario.empresasecundaria')),
                ('Nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RNomeCatalogoFerramentas', to='ferramentas.catalogodeferramentas')),
            ],
            options={
                'unique_together': {('Nome', 'EmpresaSecundaria')},
            },
        ),
    ]
