# Generated by Django 5.1 on 2024-09-06 01:28

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresasecundario', '0001_initial'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaTipoManutencao', to='empresasecundario.empresasecundaria')),
            ],
            options={
                'unique_together': {('nome', 'EmpresaSecundaria')},
            },
        ),
        migrations.CreateModel(
            name='MotivoDaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('EmpresaSecundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REmpresaSecundariaMotivoManutencao', to='empresasecundario.empresasecundaria')),
            ],
            options={
                'unique_together': {('nome', 'EmpresaSecundaria')},
            },
        ),
        migrations.CreateModel(
            name='ManutencaoDeEquipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('DataDeInicio', models.DateTimeField()),
                ('DataFim', models.DateTimeField()),
                ('Descricaodoservico', models.TextField(blank=True, max_length=500, null=True)),
                ('CatalogoManutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RCatalogoManutencao', to='manutencao.catalogomanutencao')),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REquipamentoDisponivel', to='equipamentos.equipamentodisponiveis')),
                ('MotivoManutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RMotivoManutencao', to='manutencao.motivodamanutencao')),
            ],
        ),
    ]
