# Generated by Django 5.1.4 on 2025-01-02 01:53

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zeladorx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPrimaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('CNPJ', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60)),
                ('logo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='logoprimaria/%Y/%m/%d/')),
                ('setor', models.ManyToManyField(max_length=40, to='zeladorx.typezeladoria')),
            ],
        ),
    ]
