# Generated by Django 5.1 on 2024-09-06 01:28

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPrimaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_random', models.CharField(default=utils.utils.generate_id_random, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('razao_social', models.CharField(max_length=120)),
                ('CNPJ', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado'), ('Desmobilizaçao permanente', 'Desmobilizaçao permanente'), ('Deletado', 'Deletado')], default='Mobilizado', max_length=60)),
                ('logo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='media/%Y/%m/%d/')),
            ],
        ),
    ]
