# Generated by Django 5.1.4 on 2025-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaprimaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaprimaria',
            name='CNPJ',
        ),
        migrations.AddField(
            model_name='empresaprimaria',
            name='N_unidades',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
