# Generated by Django 5.0.6 on 2024-08-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaprimaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprimaria',
            name='logo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
