# Generated by Django 5.1 on 2024-09-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaprimaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaprimaria',
            name='password',
        ),
        migrations.RemoveField(
            model_name='empresaprimaria',
            name='razao_social',
        ),
        migrations.RemoveField(
            model_name='empresaprimaria',
            name='username',
        ),
        migrations.AlterField(
            model_name='empresaprimaria',
            name='status',
            field=models.CharField(choices=[('Mobilizado', 'Mobilizado'), ('Desmobilizado', 'Desmobilizado')], default='Mobilizado', max_length=60),
        ),
    ]
