# Generated by Django 5.1 on 2024-09-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaprimaria', '0002_remove_empresaprimaria_password_and_more'),
        ('zeladorx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprimaria',
            name='setor',
            field=models.ManyToManyField(max_length=40, to='zeladorx.typezeladoria'),
        ),
    ]
